### ISSUE TITLE
[question] Jest tests failing

### ISSUE THREAD

**Issue by sibelius** [nodkz/graphql-compose-examples#1]
This is more to start a discussion around Jest snapshot feature

How can I make the jest snapshot always return the same results in the graphql server?

Should I populate the database before every run of tests?

How could I do that in a Continuos Integration environment?

**Comment by nodkz** [comment]
The main purpose of this tests to check changes in `graphql-compose` libs.
On my desktop, it works fine. I populated DB once and can re-ran tests without snapshot failures.
Some tests and queries I write in such way, that they do not depend on mongo ids or added records.

I'm a not big profi with CI, so somehow it can be done.  Need to read, search and try. But for this I have no time.

**Comment by nodkz** [comment]
When tested new functionality https://github.com/nodkz/graphql-compose-examples/commit/d1420d18559d6cf82b9f9eabb9ba23d1047c1ace, found a problem with snapshotted ids in `northwind` schema. 

Remove them from query.
